version: "3.9"

services:
  bot:
    build:
      context: .
    container_name: x-o-bot
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "8080:8080"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
